name: Python CI

on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v4.1.7

    - name: Set up Python
      uses: actions/setup-python@v5.1.1
      with:
        python-version: '3.8'
